### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by seankross** [jhudsl/jhudsl.github.io#5]
Can we change the name of this repository to jhudsl.github.io so when we make other repositories in the jhudsl organization the pages for those repositories will be under the jhudatascience.org host?

**Comment by jtleek** [comment]
Thats a great idea. would you mind making the change Sean? Or do I need to?

**Comment by seankross** [comment]
I would make it myself except I think you might have to change with whoever you bought the domain name from since jhudsl.github.io/jhudatascience now goes to jhudatascience.org. Also can you add me as a jhudsl group admin?

**Comment by jtleek** [comment]
I've invited you. Roger is the person who has the domain name so you'll have to contact him about switching it over.

**Comment by rdpeng** [comment]
Sean can we discuss around 1:15? I registered the domain name. 

-roger
--
Roger D. Peng | @rdpeng | www.biostat.jhsph.edu/~rpeng

**Comment by seankross** [comment]
@rdpeng see you then.
